<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>de.sty</groupId>
        <artifactId>i18n-parent</artifactId>
        <version>0.4.0-SNAPSHOT</version>
    </parent>

    <artifactId>i18n-example</artifactId>
    <name>i18n-example</name>
    <description>Example usage of the i18n library.</description>

    <build>
        <plugins>
            <plugin>
                <groupId>de.sty</groupId>
                <artifactId>i18n-maven-plugin</artifactId>
                <version>${project.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <className>I18nGen</className>
                    <android>true</android>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>de.sty</groupId>
            <artifactId>i18n</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
        </dependency>
    </dependencies>

</project>
